### ISSUE TITLE
simplified chinese？

### ISSUE THREAD

**Issue by Frenqy** [ZZZank/Enlightened6#12]
你好, 我想问一下这个整合包能不能直接使用E6E的翻译？

**Comment by ZZZank** [comment]
不能，而且其实也不需要

物品、流体、工具提示、JEI之类的简中翻译已经内置在En6E里了，我能想到唯一需要翻译包的地方只有任务。两者任务不一样，不能通用。

但是E6E（以及En6E）的任务只需要看物品需求就能理解，任务文本是不会提供什么关键信息的，因此不加汉化包也不会有影响
