### ISSUE TITLE
Quests were not touched with removal of RF Tools Power

### ISSUE THREAD

**Issue by BillboardEric** [ZZZank/Enlightened6#7]
One quest in Tech - Nuclear Physics and 2 quests in RFTools
![image](https://github.com/ZZZank/Enlightened6/assets/8685981/8cb97440-d367-4678-a1f6-bfc6020e79ce)
![image](https://github.com/ZZZank/Enlightened6/assets/8685981/45ed7795-fed5-4145-8c2a-e43fc5347e45)
![image](https://github.com/ZZZank/Enlightened6/assets/8685981/5b4a15e3-0a07-46ec-b11e-f1836435e72c)

**Comment by ZZZank** [comment]
Thanks for the report! A hotfix version will be avaliable soon.
